displayName=First Person
author=Zoinkwiz
support=https://github.com/Zoinkwiz/FirstPerson
description=Allows for a first-person experience without the ability to interact with anything
tags=camera
version=2.1.0
plugins=com.firstperson.FirstPersonPlugin
build=standard